[2022-05-16 17:50:52,487] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: counter.if_not_exists scheduled__2022-05-16T17:44:00+00:00 [queued]>
[2022-05-16 17:50:52,507] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: counter.if_not_exists scheduled__2022-05-16T17:44:00+00:00 [queued]>
[2022-05-16 17:50:52,508] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 17:50:52,508] {taskinstance.py:1357} INFO - Starting attempt 1 of 1
[2022-05-16 17:50:52,508] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-05-16 17:50:52,555] {manager.py:50} ERROR - Failed to extract metadata 'NoneType' object has no attribute 'host' task_type=PostgresOperator ***_dag_id=counter task_id=if_not_exists ***_run_id=scheduled__2022-05-16T17:44:00+00:00 
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/manager.py", line 40, in extract_metadata
    task_metadata = extractor.extract()
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/postgres_extractor.py", line 59, in extract
    authority=self._get_authority(),
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/postgres_extractor.py", line 131, in _get_authority
    if self.conn.host and self.conn.port:
AttributeError: 'NoneType' object has no attribute 'host'
[2022-05-16 17:50:54,215] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): if_not_exists> on 2022-05-16 17:44:00+00:00
[2022-05-16 17:50:54,222] {standard_task_runner.py:52} INFO - Started process 83 to run task
[2022-05-16 17:50:54,226] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'counter', 'if_not_exists', 'scheduled__2022-05-16T17:44:00+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/laendleimmo.py', '--cfg-path', '/tmp/tmpy0zkowiy', '--error-file', '/tmp/tmpr55epi7a']
[2022-05-16 17:50:54,227] {standard_task_runner.py:80} INFO - Job 17: Subtask if_not_exists
[2022-05-16 17:50:54,569] {task_command.py:369} INFO - Running <TaskInstance: counter.if_not_exists scheduled__2022-05-16T17:44:00+00:00 [running]> on host 7c2b8d43a7dd
[2022-05-16 17:50:54,803] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=datascience@example.com
AIRFLOW_CTX_DAG_OWNER=datascience
AIRFLOW_CTX_DAG_ID=counter
AIRFLOW_CTX_TASK_ID=if_not_exists
AIRFLOW_CTX_EXECUTION_DATE=2022-05-16T17:44:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-05-16T17:44:00+00:00
[2022-05-16 17:50:54,857] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/dbapi.py", line 181, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/postgres/hooks/postgres.py", line 86, in get_conn
    conn = deepcopy(self.connection or self.get_connection(conn_id))
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 67, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 430, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `example_db` isn't defined
[2022-05-16 17:50:54,867] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=counter, task_id=if_not_exists, execution_date=20220516T174400, start_date=20220516T175052, end_date=20220516T175054
[2022-05-16 17:50:54,904] {manager.py:50} ERROR - Failed to extract metadata 'NoneType' object has no attribute 'host' task_type=PostgresOperator ***_dag_id=counter task_id=if_not_exists ***_run_id=scheduled__2022-05-16T17:44:00+00:00 
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/manager.py", line 38, in extract_metadata
    task_metadata = extractor.extract_on_complete(task_instance)
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/base.py", line 63, in extract_on_complete
    return self.extract()
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/postgres_extractor.py", line 59, in extract
    authority=self._get_authority(),
  File "/home/airflow/.local/lib/python3.7/site-packages/openlineage/airflow/extractors/postgres_extractor.py", line 131, in _get_authority
    if self.conn.host and self.conn.port:
AttributeError: 'NoneType' object has no attribute 'host'
[2022-05-16 17:50:55,122] {standard_task_runner.py:97} ERROR - Failed to execute job 17 for task if_not_exists (The conn_id `example_db` isn't defined; 83)
[2022-05-16 17:50:55,163] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-05-16 17:50:55,263] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
